[program:lighttts]
directory=/root/autodl-tmp/LightTTS
command=/bin/bash -lc 'export PATH=/root/autodl-tmp/funasr-nano-venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin; export PYTHONPATH=/root/autodl-tmp/LightTTS:/root/autodl-tmp/LightTTS/cosyvoice; export MODELSCOPE_CACHE=/root/autodl-tmp/models; export HF_HOME=/root/autodl-tmp/hf-home; export CUDA_VISIBLE_DEVICES=0; export TTSFRD_RESOURCE=/root/autodl-tmp/models/models/iic/CosyVoice-ttsfrd/resource; export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True; exec /root/autodl-tmp/funasr-nano-venv/bin/python -u -m light_tts.server.api_server --host 127.0.0.1 --port 8080 --model_dir /root/autodl-tmp/models/models/FunAudioLLM/Fun-CosyVoice3-0.5B-2512 --data_type float16 --disable_cudagraph --httpserver_workers 1 --running_max_req_size 1 --max_total_token_num 512 --batch_max_tokens 384 --max_req_total_len 384 --encode_paral_num 1 --gpt_paral_num 1 --decode_paral_num 1 --decode_process_num 1 --encode_process_num 1 --decode_max_batch_size 1'
autostart=true
autorestart=true
startsecs=20
startretries=3
stopasgroup=true
killasgroup=true
stdout_logfile=/root/autodl-tmp/logs/lighttts.stdout.log
stderr_logfile=/root/autodl-tmp/logs/lighttts.stderr.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
environment=PYTHONUNBUFFERED="1"
